### ISSUE TITLE
GAE Deploy not working?

### ISSUE THREAD

**Issue by rvogel** [GoogleCloudPlatform/appengine-crowdguru-python#7]
Hi, I've deployed your code, just renaming it in app.yaml, and it keeps giving me a 404. If a test it local, the default (latest.html) is shown.

Log in GAE isn't helpful (transcript below):

```
2014-02-10 11:25:41.476 / 404 4ms 0kb Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36 module=default version=1
186.215.160.114 - - [10/Feb/2014:05:25:41 -0800] "GET / HTTP/1.1" 404 188 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36" "rafa-bot.appspot.com" ms=4 cpu_ms=0 cpm_usd=0.000021 app_engine_release=1.8.9 instance=00c61b117cc1f53884fc11a4fb4792539744c7
```

I've tried in Google Cloud Playground, and it worked (https://cloud-playground.appspot.com/playground/p/5417573013258240/#guru.py)

Any ideas?

**Comment by jgeewax** [comment]
Any chance you can push the code of your fork for me to take a look at ?
